spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE

      routes:
        - id: mediscreen-test
          uri: lb://MEDISCREEN-TEST
          predicates:
              - Path=/test/**
          filters:
            - RewritePath=/test, /

        - id: mediscreen-patient
          uri: lb://MEDISCREEN-PATIENT
          predicates:
            - Path=/patient/**
          filters:
            - AuthenticationFilter

        - id: mediscreen-notes
          uri: lb://MEDISCREEN-NOTES
          predicates:
            - Path=/notes/**
          filters:
            - AuthenticationFilter

        - id: mediscreen-notes
          uri: lb://MEDISCREEN-ASSESSMENT
          predicates:
            - Path=/assess/**
          filters:
            - AuthenticationFilter

        - id: mediscreen-authentication
          uri: lb://MEDISCREEN-AUTHENTICATION
          predicates:
            - Path=/auth/**

  application:
    name: MEDISCREEN-GATEWAY

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/